# Generated by Django 2.1.11 on 2019-10-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=10)),
                ('photo_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('photo_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Specialists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo_url', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=25)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='beautyApp.Service')),
            ],
        ),
        migrations.AddField(
            model_name='options',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='beautyApp.Service'),
        ),
    ]
