# Generated by Django 2.1.11 on 2019-10-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='photo_url',
        ),
    ]
